document.addEventListener("DOMContentLoaded", () => {
  const form     = document.getElementById("nameForm");
  const feedback = document.getElementById("feedback");
  const planning = document.getElementById("planning");
  const spans    = {
    g1: document.getElementById("g1"),
    g2: document.getElementById("g2"),
    g3: document.getElementById("g3")
  };

  // 1) Fetch assignments.json (auto-generated by Action)
  fetch('./assignments.json')
    .then(res => {
      if (!res.ok) throw new Error(`HTTP ${res.status}`);
      return res.json();
    })
    .then(assignments => {
      // 2) On form submit do the lookup
      form.addEventListener("submit", ev => {
        ev.preventDefault();
        feedback.textContent = '';

        // normalize accents + lower
        const normalize = s => s
          .normalize('NFD')
          .replace(/[\u0300-\u036f]/g, '')
          .trim()
          .toLowerCase();

        const first = normalize(document.getElementById('first_name').value);
        const last  = normalize(document.getElementById('last_name').value);

        if (!first || !last) {
          feedback.textContent = 'Merci de remplir prénom et nom.';
          return;
        }

        const key = `${first} ${last}`;
        const user = assignments[key];

        if (!user) {
          feedback.textContent = 'Nom non trouvé. Vérifiez l’orthographe, évitez les accents.';
          return;
        }

        // 3) Inject into the DOM
        spans.g1.textContent = user.act1 ? `Groupe ${user.act1}` : 'N/A';
        spans.g2.textContent = user.act2 ? `Groupe ${user.act2}` : 'N/A';
        spans.g3.textContent = user.act3 ? `Groupe ${user.act3}` : 'N/A';
        planning.style.display = 'block';

        // 4) Wire PDF download
        document.getElementById('downloadPdf').onclick = () => {
          html2pdf()
            .set({ margin: 0.5, filename:`planning_${first}_${last}.pdf` })
            .from(planning)
            .save();
        };
      });
    })
    .catch(err => {
      feedback.textContent = 'Impossible de charger les affectations : ' + err.message;
      console.error(err);
    });
});
